name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale due to no activity within the last 60 day'
        stale-pr-message: 'Stale due to no activity within the last 60 days'
       
