#Trigger works
name: Move assigned card
on:
  pull_request_target:
    types: [converted_to_draft]
jobs:
  moveCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1.1.4
        with:
          token: ${{ secrets.GH_AUTOMATION_TOKEN }}
          project-location: databeacon
          project-name: # PROJECT NAME
          column-name: In progress
          issue-number: ${{ github.event.number }}
