#https://github.com/marketplace/actions/assign-to-one-project
name: Auto Assign (PRs) to Project(s)

on:
  pull_request_target:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}

jobs:
  prs_handler:
    runs-on: ubuntu-latest
    name: PRs Handling Tasks
    
    steps:
    - name: Assign NEW PRs to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: '' #PROJECT LINK
        column_name: 'In progress'
