#https://github.com/marketplace/actions/assign-to-one-project
name: Auto Assign (issues) to Project(s)

on:
  issues:
    types: [opened]
#  pull_request_target:
#    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}

jobs:
  issues_handler:
    runs-on: ubuntu-latest
    name: Issues Handling Tasks
    
    steps:
    - name: Assign NEW issues to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: '' #PROJECT LINK
        column_name: 'To do'
